version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: dma
      POSTGRES_PASSWORD: dma
      POSTGRES_DB: dma_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

# Include the forum services
# To start the forum, run: docker-compose -f docker-compose.yml -f ../forum/docker-compose.yml up
